#!/bin/bash
WRKDIR=`readlink -f $(pwd)`
docker logs -f $(docker run -d -u="developer" --name elm -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK -v $(pwd)/../:/workspace/base elm $1) | sed "s#\/workspace\/base#${WRKDIR}#"
docker rm -f elm
